pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                nodejs('node-22') {
                    sh '''
                    cd app_nodejs
                    npm ci
                    npm test
                    '''
                }
            }
        }
    }    
}