---
- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker.io
    update_cache: true

- name: Add user to the docker group
  ansible.builtin.user:
    name: "{{ ansible_env.SUDO_USER }}"
    append: true
    groups: docker

- name: Reset SSH connection
  ansible.builtin.meta: "reset_connection"
